# Generated by Django 5.1 on 2025-05-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='last_name',
        ),
    ]
