# Generated by Django 5.1 on 2025-11-12 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('application_sent', 'Candidature envoyée'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('application_viewed', 'Candidature consultée'), ('slot_booked', 'Créneau réservé'), ('slot_cancelled', 'Créneau annulé'), ('zoom_link_created', 'Lien Zoom créé'), ('interview_reminder_24h', 'Rappel entretien 24h'), ('interview_reminder_10min', 'Rappel entretien 10min'), ('interview_status_changed', 'Statut entretien changé'), ('interview_completed', 'Entretien terminé'), ('new_offer', 'Nouvelle offre disponible'), ('new_programme', 'Nouveau programme ajouté'), ('zoom_programme_available', 'Lien Zoom programme disponible'), ('forum_registered', 'Inscription forum confirmée'), ('new_application', 'Nouvelle candidature reçue'), ('application_validated', 'Candidature validée'), ('application_rejected_by_recruiter', 'Candidature rejetée'), ('questionnaire_completed', 'Questionnaire complété'), ('slot_reserved', 'Créneau réservé par candidat'), ('slot_cancelled_by_candidate', 'Créneau annulé par candidat'), ('slot_created', 'Créneau créé'), ('slot_updated', 'Créneau modifié'), ('slot_deleted', 'Créneau supprimé'), ('offer_created', 'Offre créée'), ('offer_updated', 'Offre modifiée'), ('offer_deleted', 'Offre supprimée'), ('company_approved', 'Entreprise approuvée'), ('company_rejected', 'Entreprise refusée'), ('recruiter_invited', 'Invitation recruteur envoyée'), ('forum_created', 'Forum créé'), ('forum_updated', 'Forum modifié'), ('forum_deleted', 'Forum supprimé'), ('forum_phase_changed', 'Phase du forum changée'), ('programme_created', 'Programme créé'), ('programme_updated', 'Programme modifié'), ('programme_deleted', 'Programme supprimé'), ('zoom_programme_created', 'Lien Zoom programme créé'), ('speaker_added', 'Speaker ajouté'), ('company_added', 'Entreprise ajoutée'), ('company_approval_request', 'Demande approbation entreprise'), ('recruiter_registration_request', 'Demande inscription recruteur'), ('new_application_forum', 'Nouvelle candidature sur le forum'), ('new_offer_forum', 'Nouvelle offre créée')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=10)),
                ('related_object_type', models.CharField(blank=True, help_text="Type d'objet lié (application, slot, offer, etc.)", max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text="ID de l'objet lié", null=True)),
                ('action_url', models.URLField(blank=True, help_text="URL vers l'action associée", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
            },
        ),
    ]
