# Generated by Django 5.1 on 2025-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('application_sent', 'Candidature envoyée'), ('application_accepted', 'Candidature acceptée'), ('application_rejected', 'Candidature rejetée'), ('application_viewed', 'Candidature consultée'), ('slot_booked', 'Créneau réservé'), ('slot_cancelled', 'Créneau annulé'), ('zoom_link_created', 'Lien Zoom créé'), ('interview_reminder_24h', 'Rappel entretien 24h'), ('interview_reminder_10min', 'Rappel entretien 10min'), ('interview_status_changed', 'Statut entretien changé'), ('interview_completed', 'Entretien terminé'), ('new_offer', 'Nouvelle offre disponible'), ('new_programme', 'Nouveau programme ajouté'), ('zoom_programme_available', 'Lien Zoom programme disponible'), ('forum_registered', 'Inscription forum confirmée'), ('chat_request', 'Demande de discussion'), ('chat_accepted', 'Demande de discussion acceptée'), ('chat_rejected', 'Demande de discussion refusée'), ('new_message', 'Nouveau message'), ('new_application', 'Nouvelle candidature reçue'), ('application_validated', 'Candidature validée'), ('application_rejected_by_recruiter', 'Candidature rejetée'), ('questionnaire_completed', 'Questionnaire complété'), ('slot_reserved', 'Créneau réservé par candidat'), ('slot_cancelled_by_candidate', 'Créneau annulé par candidat'), ('slot_created', 'Créneau créé'), ('slot_updated', 'Créneau modifié'), ('slot_deleted', 'Créneau supprimé'), ('offer_created', 'Offre créée'), ('offer_updated', 'Offre modifiée'), ('offer_deleted', 'Offre supprimée'), ('company_approved', 'Entreprise approuvée'), ('company_rejected', 'Entreprise refusée'), ('recruiter_invited', 'Invitation recruteur envoyée'), ('forum_created', 'Forum créé'), ('forum_updated', 'Forum modifié'), ('forum_deleted', 'Forum supprimé'), ('forum_phase_changed', 'Phase du forum changée'), ('programme_created', 'Programme créé'), ('programme_updated', 'Programme modifié'), ('programme_deleted', 'Programme supprimé'), ('zoom_programme_created', 'Lien Zoom programme créé'), ('speaker_added', 'Speaker ajouté'), ('company_added', 'Entreprise ajoutée'), ('company_approval_request', 'Demande approbation entreprise'), ('recruiter_registration_request', 'Demande inscription recruteur'), ('new_application_forum', 'Nouvelle candidature sur le forum'), ('new_offer_forum', 'Nouvelle offre créée')], max_length=50),
        ),
    ]
