# Generated by Django 5.1 on 2025-10-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('banner', models.ImageField(blank=True, help_text="Photo de couverture de l'entreprise", null=True, upload_to='company_banners/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text="Description de l'entreprise")),
                ('sectors', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ForumCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('stand', models.CharField(blank=True, max_length=5, null=True)),
                ('approved', models.BooleanField(default=False, help_text="Indique si la participation de l'entreprise à ce forum est approuvée")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_participations', to='company.company')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_participants', to='forums.forum')),
            ],
            options={
                'unique_together': {('company', 'forum')},
            },
        ),
    ]
