# Generated by Django 5.1 on 2025-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcompany',
            name='stand',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
