# Generated by Django 5.1 on 2025-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_forumcompany_stand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='company.sector'),
        ),
    ]
