# Generated by Django 5.1 on 2025-06-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_sector_company_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='companies', to='company.sector'),
        ),
    ]
