# Generated by Django 5.1 on 2025-06-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_sectors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sectors',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.AddField(
            model_name='company',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
