# Generated by Django 5.1 on 2025-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_sectors_delete_sector_company_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved',
            field=models.BooleanField(default=False, help_text="Indique si l'entreprise est approuvée pour participer aux forums"),
        ),
    ]
