# Generated by Django 5.1 on 2025-07-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='approved',
        ),
        migrations.AddField(
            model_name='forumcompany',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
