# Generated by Django 5.1 on 2025-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_company_approved_forumcompany_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcompany',
            name='approved',
            field=models.BooleanField(default=False, help_text="Indique si la participation de l'entreprise à ce forum est approuvée"),
        ),
    ]
