# Generated by Django 5.1 on 2025-08-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_forumcompany_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text="Description de l'entreprise"),
        ),
    ]
