# Generated by Django 5.1 on 2025-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, help_text='Photo de couverture 2624x560px', null=True, upload_to='company_banners/'),
        ),
    ]
