# Generated by Django 5.1 on 2025-09-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='banner',
            field=models.ImageField(blank=True, help_text="Photo de couverture de l'entreprise", null=True, upload_to='company_banners/'),
        ),
    ]
