# Generated by Django 5.1 on 2025-10-20 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0002_forum_interview_end_forum_interview_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAgendaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date du créneau')),
                ('start_time', models.TimeField(help_text='Heure de début')),
                ('end_time', models.TimeField(help_text='Heure de fin')),
                ('type', models.CharField(choices=[('video', 'Visioconférence'), ('phone', 'Téléphone')], default='video', help_text="Type d'entretien", max_length=10)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Durée en minutes')),
                ('description', models.TextField(blank=True, help_text='Description du créneau', null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('booked', 'Réservé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='available', max_length=20)),
                ('meeting_link', models.URLField(blank=True, help_text='Lien de la visioconférence', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text="Notes de l'entretien", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, help_text='Candidat qui a réservé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_slots', to='forums.forum')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('recruiter', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
