# Generated by Django 5.1 on 2025-10-20 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forum_interview_end_forum_interview_start_and_more'),
        ('recruiters', '0005_remove_recruiter_bio_alter_recruiter_title'),
        ('virtual', '0002_questionnaire_question_questionnaireresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_responses', models.JSONField(blank=True, help_text='Réponses au questionnaire', null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Consultée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes du recruteur', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_applications', to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_applications', to='forums.forum')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_applications', to='recruiters.offer')),
                ('selected_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='virtual.virtualagendaslot')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'offer')},
            },
        ),
    ]
