# Generated by Django 5.1 on 2025-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0003_virtualapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualapplication',
            name='interview_status',
            field=models.CharField(choices=[('scheduled', 'Programmé'), ('inProgress', 'En cours'), ('completed', 'Terminé')], default='scheduled', help_text="Statut de l'entretien", max_length=20),
        ),
    ]
