# Generated by Django 5.1 on 2025-07-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company'), ('admin', 'Admin'), ('organizer', 'Organizer')], default='candidate', max_length=20),
        ),
    ]
