# Generated by Django 5.1 on 2025-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidate_company_remove_entreprise_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
