# Generated by Django 5.1 on 2025-10-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_last_login'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
    ]
