# Generated by Django 5.1 on 2025-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_0002_add_last_login_0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Paris', help_text="Fuseau horaire de l'utilisateur", max_length=50),
        ),
    ]
