# Generated by Django 5.1 on 2025-05-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
