# Generated by Django 5.1 on 2025-05-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
