# Generated by Django 5.1 on 2025-05-11 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usertoken_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='new_email',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
