# Generated by Django 5.1 on 2025-05-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usertoken_new_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='new_email',
            new_name='email',
        ),
    ]
