# Generated by Django 5.1 on 2025-10-10 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateforumprogress',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forum'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_languages', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='education',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='candidatelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.language'),
        ),
        migrations.AddField(
            model_name='skill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='candidates.candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateforumprogress',
            unique_together={('candidate', 'forum')},
        ),
        migrations.AlterUniqueTogether(
            name='candidatelanguage',
            unique_together={('candidate', 'language')},
        ),
    ]
