# Generated by Django 5.1 on 2025-06-13 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_education_end_date_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
