# Generated by Django 5.1 on 2025-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(blank=True, choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
