# Generated by Django 5.1 on 2025-09-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, help_text='Biographie du candidat'),
        ),
    ]
