# Generated by Django 5.1 on 2025-09-08 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_bio'),
        ('forums', '0010_programme_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateForumProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_companies', models.JSONField(default=list, help_text='Liste des IDs des entreprises visitées')),
                ('company_notes', models.JSONField(default=dict, help_text='Notes par entreprise {company_id: note}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_progress', to='candidates.candidate')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
            ],
            options={
                'verbose_name': 'Progression Forum Candidat',
                'verbose_name_plural': 'Progressions Forum Candidats',
                'unique_together': {('candidate', 'forum')},
            },
        ),
    ]
