# Generated by Django 5.1 on 2025-09-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidateforumprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='preferred_contract_type',
        ),
    ]
