# Generated by Django 5.1 on 2025-11-12 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_duplicate_conversations(apps, schema_editor):
    """Supprime les conversations en double avant d'appliquer la contrainte unique"""
    Conversation = apps.get_model('chat', 'Conversation')
    Message = apps.get_model('chat', 'Message')
    
    # Trouver les doublons basés sur forum, company, candidate
    from django.db.models import Count, Min
    
    # Récupérer tous les groupes de conversations avec les mêmes forum, company, candidate
    duplicates = (
        Conversation.objects
        .values('forum_id', 'company_id', 'candidate_id')
        .annotate(count=Count('id'), min_id=Min('id'))
        .filter(count__gt=1)
    )
    
    # Pour chaque groupe de doublons, garder seulement la conversation la plus ancienne
    for dup in duplicates:
        conversations = Conversation.objects.filter(
            forum_id=dup['forum_id'],
            company_id=dup['company_id'],
            candidate_id=dup['candidate_id']
        ).order_by('created_at')
        
        # Garder la première (la plus ancienne) et supprimer les autres
        keep = conversations.first()
        if keep:
            # Transférer les messages vers la conversation conservée
            for conv in conversations.exclude(id=keep.id):
                Message.objects.filter(conversation=conv).update(conversation=keep)
            # Supprimer les conversations dupliquées
            conversations.exclude(id=keep.id).delete()


def reverse_remove_duplicates(apps, schema_editor):
    """Fonction de rollback - ne fait rien car on ne peut pas restaurer les doublons supprimés"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('company', '0001_initial'),
        ('forums', '0003_programme_enable_zoom_programme_meeting_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # D'abord, supprimer l'ancienne contrainte unique
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        # Ajouter le champ company
        migrations.AddField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='company.company'),
            preserve_default=False,
        ),
        # Modifier le champ recruiter
        migrations.AlterField(
            model_name='conversation',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_conversations', to=settings.AUTH_USER_MODEL),
        ),
        # Supprimer les doublons AVANT d'appliquer la nouvelle contrainte unique
        migrations.RunPython(remove_duplicate_conversations, reverse_remove_duplicates),
        # Enfin, appliquer la nouvelle contrainte unique
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('forum', 'company', 'candidate')},
        ),
    ]
