# Generated by Django 5.1 on 2025-11-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_conversation_recruiter_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_forum_i_dfb697_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_updated_1f6ffe_idx',
        ),
    ]
