# Generated by Django 5.1 on 2025-10-10 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_initial'),
        ('company', '0001_initial'),
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='recruiter_photos/')),
                ('title', models.CharField(blank=True, choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur'), ('Autre', 'Autre')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='company.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(choices=[('IT', 'Informatique'), ('Marketing', 'Marketing'), ('Commerce', 'Commerce'), ('RH', 'Ressources Humaines'), ('Finance', 'Finance'), ('Santé', 'Santé'), ('Éducation', 'Éducation'), ('BTP', 'BTP / Construction'), ('Logistique', 'Logistique / Transport'), ('Technologie', 'Technologie / IT'), ('Autre', 'Autre')], max_length=100)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ("Contrat d'apprentissage", "Contrat d'apprentissage"), ('Contrat de professionnalisation', 'Contrat de professionnalisation')], max_length=50)),
                ('profile_recherche', models.TextField(blank=True, help_text='Profil recherché pour ce poste')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('expired', 'Expirée')], default='draft', max_length=20)),
                ('start_date', models.DateField(default='2024-01-01', help_text='Date de début du poste')),
                ('experience_required', models.CharField(choices=[('0-1', '0-1 an'), ('1-3', '1-3 ans'), ('3-5', '3-5 ans'), ('5+', '5+ ans')], default='1-3', help_text="Années d'expérience requises", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='company.company')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='forums.forum')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='recruiters.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_offers', to='candidates.candidate')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recruiters.offer')),
            ],
            options={
                'verbose_name': 'Offre Favorite',
                'verbose_name_plural': 'Offres Favorites',
                'unique_together': {('candidate', 'offer')},
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='candidates.candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='company.company')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='forums.forum')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='recruiters.recruiter')),
            ],
            options={
                'unique_together': {('candidate', 'recruiter', 'forum')},
            },
        ),
        migrations.CreateModel(
            name='RecruiterForumParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_participations', to='forums.forum')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_participations', to='recruiters.recruiter')),
            ],
            options={
                'unique_together': {('recruiter', 'forum')},
            },
        ),
    ]
