# Generated by Django 5.1 on 2025-10-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='recruiter_role',
            field=models.CharField(choices=[('recruiter', 'Recruteur'), ('manager', 'Manager')], default='recruiter', help_text="Rôle du recruteur dans l'entreprise", max_length=20),
        ),
    ]
