# Generated by Django 5.1 on 2025-10-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_recruiter_recruiter_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='recruiter_role',
        ),
    ]
