# Generated by Django 5.1 on 2025-05-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forum_organizer'),
        ('recruiters', '0002_recruiterforumparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='forums',
            field=models.ManyToManyField(blank=True, related_name='recruiters', to='forums.forum'),
        ),
        migrations.DeleteModel(
            name='RecruiterForumParticipation',
        ),
    ]
