# Generated by Django 5.1 on 2025-06-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='sector',
            field=models.CharField(choices=[('IT', 'Informatique'), ('Marketing', 'Marketing'), ('Commerce', 'Commerce'), ('RH', 'Ressources Humaines'), ('Finance', 'Finance')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
