# Generated by Django 5.1 on 2025-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_remove_recruiter_recruiter_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='bio',
            field=models.TextField(blank=True, help_text='Biographie du recruteur'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='title',
            field=models.CharField(blank=True, choices=[], max_length=20),
        ),
    ]
