# Generated by Django 5.1 on 2025-06-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_education_end_date_education_start_date_and_more'),
        ('recruiters', '0004_offer_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_offers', to='candidates.candidate')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='recruiters.offer')),
            ],
            options={
                'verbose_name': 'Offre Favorite',
                'verbose_name_plural': 'Offres Favorites',
                'unique_together': {('candidate', 'offer')},
            },
        ),
    ]
