# Generated by Django 5.1 on 2025-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_recruiter_bio_alter_recruiter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='bio',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='title',
            field=models.CharField(blank=True, choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
