# Generated by Django 5.1 on 2025-06-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_favoriteoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='title',
            field=models.CharField(blank=True, choices=[('Madame', 'Madame'), ('Monsieur', 'Monsieur'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
