# Generated by Django 5.1 on 2025-06-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_recruiter_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
