# Generated by Django 5.1 on 2025-06-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_rename_phone_number_recruiter_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='photo',
            new_name='profile_picture',
        ),
    ]
