# Generated by Django 5.1 on 2025-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0009_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ("Contrat d'apprentissage", "Contrat d'apprentissage"), ('Contrat de professionnalisation', 'Contrat de professionnalisation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sector',
            field=models.CharField(choices=[('IT', 'Informatique'), ('Marketing', 'Marketing'), ('Commerce', 'Commerce'), ('RH', 'Ressources Humaines'), ('Finance', 'Finance'), ('Santé', 'Santé'), ('Éducation', 'Éducation'), ('BTP', 'BTP / Construction'), ('Logistique', 'Logistique / Transport'), ('Technologie', 'Technologie / IT'), ('Autre', 'Autre')], max_length=100),
        ),
    ]
