# Generated by Django 5.1 on 2025-08-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0010_alter_offer_contract_type_alter_offer_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='profile_recherche',
            field=models.TextField(blank=True, help_text='Profil recherché pour ce poste'),
        ),
    ]
