# Generated by Django 5.1 on 2025-09-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0011_offer_profile_recherche'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='experience_required',
            field=models.CharField(choices=[('0-1', '0-1 an'), ('1-3', '1-3 ans'), ('3-5', '3-5 ans'), ('5+', '5+ ans')], default='1-3', help_text="Années d'expérience requises", max_length=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default='2024-01-01', help_text='Date de début du poste'),
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('expired', 'Expirée')], default='draft', max_length=20),
        ),
    ]
