# Generated by Django 5.1 on 2025-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='interview_end',
            field=models.DateTimeField(blank=True, help_text='Fin de la phase des entretiens', null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='interview_start',
            field=models.DateTimeField(blank=True, help_text='Début de la phase des entretiens', null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='jobdating_start',
            field=models.DateTimeField(blank=True, help_text='Début de la phase jobdating/traitement', null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='preparation_end',
            field=models.DateTimeField(blank=True, help_text='Fin de la phase de préparation', null=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='preparation_start',
            field=models.DateTimeField(blank=True, help_text='Début de la phase de préparation', null=True),
        ),
    ]
