# Generated by Django 5.1 on 2025-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_forum_interview_end_forum_interview_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='enable_zoom',
            field=models.BooleanField(default=False, help_text='Générer automatiquement un lien Zoom pour cette conférence'),
        ),
        migrations.AddField(
            model_name='programme',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Lien de la réunion Zoom', null=True),
        ),
    ]
