# Generated by Django 5.1 on 2025-06-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('rqth', models.BooleanField(default=False)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='forums.forumregistration')),
            ],
        ),
    ]
