# Generated by Django 5.1 on 2025-11-13 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
        ('forums', '0003_programme_enable_zoom_programme_meeting_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_registrations', to='candidates.candidate')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='forums.programme')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('programme', 'candidate')},
            },
        ),
    ]
