# Generated by Django 5.1 on 2025-06-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_candidatesearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesearch',
            name='registration',
        ),
        migrations.AddField(
            model_name='forumregistration',
            name='search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_reverse', to='forums.candidatesearch'),
        ),
    ]
