# Generated by Django 5.1 on 2025-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_remove_candidatesearch_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesearch',
            name='contract_type',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='candidatesearch',
            name='sector',
            field=models.JSONField(default=list),
        ),
    ]
