# Generated by Django 5.1 on 2025-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_alter_candidatesearch_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='end_date',
            field=models.DateField(default='2025-07-22'),
        ),
        migrations.AddField(
            model_name='forum',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='forum',
            name='start_date',
            field=models.DateField(default='2025-07-22'),
        ),
        migrations.AddField(
            model_name='forum',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
