# Generated by Django 5.1 on 2025-07-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_forum_end_date_forum_end_time_forum_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='date',
        ),
    ]
