# Generated by Django 5.1 on 2025-08-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0008_remove_forum_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speaker_photos/')),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='forum',
            name='type',
            field=models.CharField(choices=[('hybride', 'Hybride'), ('presentiel', 'Présentiel'), ('virtuel', 'Virtuel')], max_length=20),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='17:00')),
                ('location', models.CharField(max_length=200)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='forums.forum')),
                ('speakers', models.ManyToManyField(blank=True, related_name='programmes', to='forums.speaker')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
    ]
