# Generated by Django 5.1 on 2025-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_speaker_alter_forum_type_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='programme_photos/'),
        ),
    ]
